version: "3.7"

services:
   covidhk:
      container_name: covidhk
      user: root
      environment:
         TZ: "Asia/Hong_Kong"
         GRANT_SUDO: "yes"
      image: jupyter/datascience-notebook
      ports:
         - "8888:8888/tcp"
      volumes:
         - .:/home/jovyan/work
